/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppVisualizerRouteImport } from './routes/app.visualizer'
import { Route as AppTrustRouteImport } from './routes/app.trust'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppOwnerRouteImport } from './routes/app.owner'
import { Route as AppMapRouteImport } from './routes/app.map'
import { Route as AppGreenCreditsRouteImport } from './routes/app.green-credits'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppSessionIdRouteImport } from './routes/app.session.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppVisualizerRoute = AppVisualizerRouteImport.update({
  id: '/visualizer',
  path: '/visualizer',
  getParentRoute: () => AppRoute,
} as any)
const AppTrustRoute = AppTrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppGreenCreditsRoute = AppGreenCreditsRouteImport.update({
  id: '/green-credits',
  path: '/green-credits',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionIdRoute = AppSessionIdRouteImport.update({
  id: '/session/$id',
  path: '/session/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/green-credits': typeof AppGreenCreditsRoute
  '/app/map': typeof AppMapRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trust': typeof AppTrustRoute
  '/app/visualizer': typeof AppVisualizerRoute
  '/app/': typeof AppIndexRoute
  '/app/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/green-credits': typeof AppGreenCreditsRoute
  '/app/map': typeof AppMapRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trust': typeof AppTrustRoute
  '/app/visualizer': typeof AppVisualizerRoute
  '/app': typeof AppIndexRoute
  '/app/session/$id': typeof AppSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/green-credits': typeof AppGreenCreditsRoute
  '/app/map': typeof AppMapRoute
  '/app/owner': typeof AppOwnerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/trust': typeof AppTrustRoute
  '/app/visualizer': typeof AppVisualizerRoute
  '/app/': typeof AppIndexRoute
  '/app/session/$id': typeof AppSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/green-credits'
    | '/app/map'
    | '/app/owner'
    | '/app/settings'
    | '/app/trust'
    | '/app/visualizer'
    | '/app/'
    | '/app/session/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/analytics'
    | '/app/green-credits'
    | '/app/map'
    | '/app/owner'
    | '/app/settings'
    | '/app/trust'
    | '/app/visualizer'
    | '/app'
    | '/app/session/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/analytics'
    | '/app/green-credits'
    | '/app/map'
    | '/app/owner'
    | '/app/settings'
    | '/app/trust'
    | '/app/visualizer'
    | '/app/'
    | '/app/session/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/visualizer': {
      id: '/app/visualizer'
      path: '/visualizer'
      fullPath: '/app/visualizer'
      preLoaderRoute: typeof AppVisualizerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/trust': {
      id: '/app/trust'
      path: '/trust'
      fullPath: '/app/trust'
      preLoaderRoute: typeof AppTrustRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/owner': {
      id: '/app/owner'
      path: '/owner'
      fullPath: '/app/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/map': {
      id: '/app/map'
      path: '/map'
      fullPath: '/app/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/green-credits': {
      id: '/app/green-credits'
      path: '/green-credits'
      fullPath: '/app/green-credits'
      preLoaderRoute: typeof AppGreenCreditsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/session/$id': {
      id: '/app/session/$id'
      path: '/session/$id'
      fullPath: '/app/session/$id'
      preLoaderRoute: typeof AppSessionIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppGreenCreditsRoute: typeof AppGreenCreditsRoute
  AppMapRoute: typeof AppMapRoute
  AppOwnerRoute: typeof AppOwnerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrustRoute: typeof AppTrustRoute
  AppVisualizerRoute: typeof AppVisualizerRoute
  AppIndexRoute: typeof AppIndexRoute
  AppSessionIdRoute: typeof AppSessionIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppGreenCreditsRoute: AppGreenCreditsRoute,
  AppMapRoute: AppMapRoute,
  AppOwnerRoute: AppOwnerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrustRoute: AppTrustRoute,
  AppVisualizerRoute: AppVisualizerRoute,
  AppIndexRoute: AppIndexRoute,
  AppSessionIdRoute: AppSessionIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
